### model
model_name_or_path: /home/ma-user/work/lyf/model/Qwen3_5-9B
# image_max_pixels: 401408
video_max_pixels: 602112 #602112 401408 301056
video_fps: 8.0              # ← 新增：提升动作采样率
# video_maxlen: 32            # ← 新增：限制最大帧数，防止 OOM
# max_steps: 200
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 128
lora_target: all
# lora_target: q_proj,v_proj,o_proj,gate_proj,up_proj,down_proj,mlp.gate_proj,mlp.up_proj,mlp.down_proj #k_proj,
# lora_dropout: 0.05              # 这里也可以不加，数据量比较小的情况下
enable_thinking: false
additional_target: visual.merger
### dataset
# dataset_dir: cache/ads_LM_data/vru_lane_multi/train_data_merge
dataset: crash_1cam_2cls_3s_39k
# dataset: pullover_binary_14k
template: qwen3_5_nothink
cutoff_len: 32768
max_samples: null
# max_samples: 100
overwrite_cache: true
dataloader_num_workers: 24
preprocessing_num_workers: 160
# data_shared_file_system: true
### output
output_dir: /home/ma-user/work/lyf/outmodel/crash_1cam_2cls_3s_39k_bs256
logging_dir: /home/ma-user/work/lyf/log_dir
logging_steps: 25
save_steps: 25
plot_loss: true
overwrite_output_dir: true
save_only_model: false
# load_best_model_at_end: true

flash_attn: fa2             # ← 新增：强制使用 FlashAttention-2，极其节省显存
# upcast_layernorm: true      # ← 混合精度下提升稳定性
gradient_checkpointing: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.5e-5
max_grad_norm: 1.0
num_train_epochs: 8
lr_scheduler_type: cosine
warmup_ratio: 0.0075
bf16: true
ddp_timeout: 180000000
# ddp_timeout: 40000
# resume_from_checkpoint: /home/ma-user/work/outmodel/avoidance_cot_v1/checkpoint-40

### swanlab
report_to: tensorboard

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
### eval
val_size: 0.05                           # 使用 2% 数据作为验证集（约 360 条）
per_device_eval_batch_size: 1           # 多模态 eval batch size=1 更稳定
eval_strategy: steps                    # 按 step 评估
eval_steps: 25                          # 与 save_steps 一致，每 50 steps 验证一次

